version: '3'

services:
  hangman:
    build:
      context: .
      args:
        username: hangman
    container_name: hangman
    hostname: hangman
    user: root
    entrypoint: 'yarn dev'
    ports:
      - 8080:8080
    environment:
      HOST: 0.0.0.0
    networks:
      - hangman
    volumes:
    - .:/hangman

networks:
  hangman:
