version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: hangman_api
    volumes:
    - ./api:/api
    ports:
    - 4000:4000
    depends_on:
      - database
  database:
    container_name: hangman_pgdb
    image: postgres:9.6

