version: '3'

services:

  #api:
    #build:
      #context: .
      #dockerfile: ./api/Dockerfile
      #args:
        #user_id: $UID
        #username: hangman_api
        #app_path: /api
    #container_name: hangman_api
    #hostname: hangman_api
    #user: hangman_api
    #entrypoint: "mix phx.server"
    #volumes:
    #- ./api:/api
    #ports:
    #- 4000:4000
    #depends_on:
    #- database
    #networks:
      #hangman:
        #aliases:
        #- api


  #database:
    #container_name: hangman_pgdb
    #image: postgres:9.6
    #volumes:
    #- /var/lib/docker/hangman_pgdb:/var/lib/postgresql/data
    #networks:
    #- hangman


  frontend:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
      args:
        user_id: $UID
        username: hangman_frontend
        app_path: /frontend
    container_name: hangman_frontend
    hostname: hangman_frontend
    user: root
    entrypoint: 'yarn dev'
    ports:
      - 8080:8080
    environment:
      HOST: 0.0.0.0
    #depends_on:
      #- api
    networks:
      - hangman
    volumes:
    - ./front-end:/frontend

networks:
  hangman:
